version: '3.8'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    container_name: cont-postgres-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - net-app

networks:
  net-app:
    driver: bridge
    name: net-app   
    