version: '3.8'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: advancedb

    container_name: cont-postgres-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - net-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  # pg client
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hadmarcano@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    container_name: cont-pgadmin
    networks:
      - net-app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy

networks:
  net-app:
    driver: bridge
    name: net-app   
    